# Generated by Django 3.2.5 on 2022-05-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True


    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(null=True)),
                ('date', models.DateField(unique=True)),
                ('positive', models.IntegerField(null=True)),
                ('negative', models.IntegerField(null=True)),
                ('neutral', models.IntegerField(null=True)),
            ],
        ),
    ]
